name: Release Docker image

run-name: Release ${{ github.ref_name }}

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v0.0.0-dev.[0-9]+

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: tag
        run: |
          tag=${{ github.ref_name }}
          version=${tag:1}
          dev=${{ startsWith(github.ref_name, 'v0.0.0-dev') }}
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "dev=$dev" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set image metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: mattsyms/wait-for
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}},enable=${{ steps.tag.outputs.dev == 'false' }}
            type=semver,pattern={{major}},enable=${{ steps.tag.outputs.dev == 'false' }}
            type=raw,value=latest,enable=${{ steps.tag.outputs.dev == 'false' }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish to Docker Hub
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}

      - name: Update Docker Hub description
        if: steps.tag.outputs.dev == 'false'
        uses: peter-evans/dockerhub-description@v4
        with:
          repository: mattsyms/wait-for
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          short-description: ${{ github.event.repository.description }}
